name: 'workflows日志自动清理'

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  del_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 删除workflows日志
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: '7'
